### ISSUE TITLE
Job Id should be long

### ISSUE THREAD

**Issue by ivankozyrev** [ubisoft/NGitLab#724] opened 2024-07-18 19:56 UTC
I'm getting deserialization error for `GetJobs` method : "System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $[0].id | LineNumber: 0 | BytePositionInLine: 17."

I guess that Id property type should be changed from int to long, may be it should be done for all other Id properties.

```
var pipelines = client.GetPipelines(projectId);
var pipeline = pipelines.Create(new PipelineCreate()
        {
            Ref = "main"
        });
var jobs = pipelines.GetJobs(pipeline.Id);
```

**Comment by louis-z** [comment] 2024-08-05 15:18
Unfortunately the GitLab API doc is not always clear about the bit width of its various IDs, but I think you're right. We would probably need to consider making many (if not all) numeric IDs 64-bit IDs.

**Comment by louis-z** [comment] 2024-09-09 12:12
Duplicate of #491

**Closed as completed by louis-z** 2024-09-09 12:12 UTC
